name: "ai_project_codex"
version: "1.0.0"
config-version: 2

profile: "fp_hack_hackathon"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
packages-install-path: "dbt_packages_vendor"

clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_packages_vendor"

models:
  ai_project_codex:
    staging:
      +schema: b2_int
      +materialized: table
    intermediate:
      +schema: b2_int
      +materialized: view
    marts:
      +schema: b2_mart
      +materialized: table
